### ISSUE TITLE
Yarn build on a clean clone fails

### ISSUE THREAD

**Issue by chitalian** [supabase-community/supabase-on-aws#29]
# Bug report

## Describe the bug

```
Bundling asset Supabase/Studio/Repository/ImportFunction/Code/Stage...
unknown shorthand flag: 'u' in -u
/Users/justin/Documents/repos/promptzero/helicone-on-aws/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:468
      throw new Error(`Failed to bundle asset ${this.node.path}, bundle output is located at ${bundleErrorDir}: ${err}`);
            ^
Error: Failed to bundle asset Supabase/Studio/Repository/ImportFunction/Code/Stage, bundle output is located at /Users/justin/Documents/repos/promptzero/helicone-on-aws/cdk.out/asset.cacf47d179251c214c8728ecc90ed5906d9426afd63b1f1ee6992e03197368bc-error: Error: docker exited with status 16
--> Command: docker run --rm -u root -v "/Users/justin/Documents/repos/promptzero/helicone-on-aws/src/functions/copy-git-repo:/asset-input:delegated" -v "/Users/justin/Documents/repos/promptzero/helicone-on-aws/cdk.out/asset.cacf47d179251c214c8728ecc90ed5906d9426afd63b1f1ee6992e03197368bc:/asset-output:delegated" -w "/asset-input" "public.ecr.aws/sam/build-python3.9:latest-x86_64" "/bin/bash" -c "mkdir -p /var/task/local/{bin,lib}&&cp /usr/bin/git /usr/libexec/git-core/git-remote-https /usr/libexec/git-core/git-remote-http /var/task/local/bin&&ldd /usr/bin/git | awk 'NF == 4 { system(\"cp \" $3 \" /var/task/local/lib/\") }'&&ldd /usr/libexec/git-core/git-remote-https | awk 'NF == 4 { system(\"cp \" $3 \" /var/task/local/lib/\") }'&&ldd /usr/libexec/git-core/git-remote-http | awk 'NF == 4 { system(\"cp \" $3 \" /var/task/local/lib/\") }'&&pip install -r requirements.txt -t /var/task&&cp -au /asset-input/index.py /var/task&&cp -aur /var/task/* /asset-output"
    at AssetStaging.bundle (/Users/justin/Documents/repos/promptzero/helicone-on-aws/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:468:13)
    at AssetStaging.stageByBundling (/Users/justin/Documents/repos/promptzero/helicone-on-aws/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:331:10)
    at stageThisAsset (/Users/justin/Documents/repos/promptzero/helicone-on-aws/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:197:35)
    at Cache.obtain (/Users/justin/Documents/repos/promptzero/helicone-on-aws/node_modules/aws-cdk-lib/core/lib/private/cache.ts:24:13)
    at new AssetStaging (/Users/justin/Documents/repos/promptzero/helicone-on-aws/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:222:44)
    at new Asset (/Users/justin/Documents/repos/promptzero/helicone-on-aws/node_modules/aws-cdk-lib/aws-s3-assets/lib/asset.ts:128:21)
    at AssetCode.bind (/Users/justin/Documents/repos/promptzero/helicone-on-aws/node_modules/aws-cdk-lib/aws-lambda/lib/code.ts:278:20)
    at new Function (/Users/justin/Documents/repos/promptzero/helicone-on-aws/node_modules/aws-cdk-lib/aws-lambda/lib/function.ts:726:29)
    at new Repository (/Users/justin/Documents/repos/promptzero/helicone-on-aws/src/aws-amplify-hosting.ts:162:27)
    at new AmplifyHosting (/Users/justin/Documents/repos/promptzero/helicone-on-aws/src/aws-amplify-hosting.ts:32:24)

Subprocess exited with error 1
👾 Task "build » post-compile » synth:silent" failed when executing "cdk synth -q" (cwd: /Users/justin/Documents/repos/promptzero/helicone-on-aws)
```

## To Reproduce

Clone the repo and run `yarn && yarn build`

## System information

- OS: [macOS]

```
npx cdk --version
2.73.0 (build 43e681e)
```
```
docker --version    
Docker version 20.10.12, build e91ed57
```
```
npx projen --version
0.70.5
```

**Comment by chitalian** [comment]
nvm this was because my context was not default.
